name: deploy github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1


jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup nightly rust toolchain with caching
        uses: brndnmtthws/rust-action@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          enable-sccache: "false"

      - name: install wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown

      - name: install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli

      # - name: install wasm-opt
      #   run: cargo install wasm-opt --locked

      - name: build wasm artifacts
        run: cargo build -p bevy_burn_human --target wasm32-unknown-unknown --release --no-default-features

      # - name: optimize wasm artifacts
      #   run: wasm-opt -O -ol 100 -s 100 -o ./target/wasm32-unknown-unknown/release/bevy_burn_human_opt.wasm ./target/wasm32-unknown-unknown/release/bevy_burn_human.wasm

      - name: generate bindings with wasm-bindgen
        run: wasm-bindgen --out-dir ./crates/bevy_burn_human/www/out/ --target web ./target/wasm32-unknown-unknown/release/bevy_burn_human.wasm

      - name: copy assets
        run: |
          mkdir -p ./crates/bevy_burn_human/www/assets
          cp -R ./assets/. ./crates/bevy_burn_human/www/assets/

      - name: deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./crates/bevy_burn_human/www
          branch: www